### ISSUE TITLE
Barra de Navegação

### ISSUE THREAD

**Issue by Zev07** [Zev07/Zev07#1]

**Comment by jhonysab** [comment]
# Segue o HTML
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jhony // Zevv</title>
    <link rel="stylesheet" href="style.css">
<link rel="shortcut icon" href="note2.ico" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body style="background-color: #980414;">
    
    <ul class="nav justify-content-center">
         <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Projetos</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Separated link</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Sobre</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Redes sociais</a>
            
          </li>
      </ul>

    <script  src=script.js></script>  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

**Comment by jhonysab** [comment]
# Segue o CSS:
.nav.nav.justify-content-center{
    background-color: black;
    gap: 20px;
    height: 80px;
    padding: 25px;
}
.nav-item .nav-link{
    color:white ;
    display:flex;
}

.nav.nav-tabs {
    background-color: #8e7575;
}

.nav.nav.justify-content-center .nav-item .nav-link.disabled{
    color: green;
}
.nav.nav.justify-content-center .dropdown-toggle::after {
    display: none ;
}
